### ISSUE TITLE
Easy test token minting in the web ui

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/webui#11]
Expose the mint button if the token supports it, this should make funding accounts for testing easier.

**Comment by kelsos** [comment]
I think it would be better to only enable this for testnets. Also, this checking mechanism has to integrate with the BatchManager, to avoid the performance issues we had with a big number of registered tokens.

**Comment by kelsos** [comment]
@manuelwedler 

The requirements for the mint button are:
- It doesn't work when the network is mainnet https://github.com/raiden-network/webui/blob/ad4ce8b158c8ebc7e9486984a193040697af3bd2/src/app/utils/network-info.ts#L6
- On the token networks if you are not in the mainnet it should display a button that allows you to mint tokens.
- The mint button should attempt to call the `function mint(uint amount)` function with a predefined amount of `100` or `1000`.
https://github.com/raiden-network/raiden-contracts/blob/acd697fec11be7e008abaf3abf638b1ceff8d253/raiden_contracts/data/source/test/CustomToken.sol#L69
- Notify the user if the mint action was successful
- Show an error message if mint is not available for the token


Optionally
----------- 
For future consideration, it seems that the W-ETH ([you can find the token addresses here](https://blog.0xproject.com/canonical-weth-migration-8a7ab6caca71)) contract has a `function deposit() public payable` instead of mint. Maybe It would make sense to provide a W-ETH deposit function in the WebUI @christianbrb what do you think about that?

**Comment by manuelwedler** [comment]
The WebUI is currently not sending Transactions on its own, only using the Raiden API. For the minting feature it would be necessary to unlock the account and send the transaction from the WebUI OR send the transaction by the Raiden client itself. Any ideas on that?

**Comment by kelsos** [comment]
@hackaugusto @rakanalh Any suggestions on how this could be done? I cannot see any other option than passing somehow through the Raiden API for this.

**Comment by rakanalh** [comment]
I can support you on this next week. Let's create an issue for it.
