### ISSUE TITLE
Token input field misses decimals partly when converting from integer input on Firefox

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#138]
## Describe the bug
Firefox can only handle up to 16 decimal points for input fields and if there are more they get cut off. This happens in the token amount input field when converting an integer input to the decimal input. While the form control sill has the correct value internally the displayed value is cut off.

## Steps to reproduce
Open payment dialog with a token with 18 decimals.
Uncheck decimals and input e.g. 111.
Check decimals again.
The value was converted to 0.0000000000000001.

## Expected behavior
The view displays the same value as the form control holds.

## System:
 - Firefox 68.0.1
 - WebUI v0.9.2

**Comment by kelsos** [comment]
@manuelwedler Is this issue on Firefox? Did you check with Chrome? Does the same thing happen? if you try and uncheck the decimals again do you see 111?

If you encountered this on Firefox then this is not a rounding/conversion error but and issue with the number input of Firefox. The problem is that then number input on Firefox can only handle up to 16 decimal points. If you add more than that then they get cut off.

**Comment by manuelwedler** [comment]
@kelsos You are right. This issue does only happen on Firefox. Is there any solution to this?

**Comment by kelsos** [comment]
@manuelwedler if firefox doesn't change the way the numeric input works, I guess the only way would be to use a normal text input customized to work as a numeric input.

**Comment by manuelwedler** [comment]
accomplished by redesign #253
