### ISSUE TITLE
ENS name is not resolved

### ISSUE THREAD

**Issue by nephix** [raiden-network/webui#297]
## Steps to reproduce
Click on Channels
Click on +
Enter as target hub.raiden.eth

## Expected behavior

Gets resolved  to an address

## Screenshots

![Screenshot 2020-03-12 at 14 36 34](https://user-images.githubusercontent.com/3169205/76527730-fb63f180-646f-11ea-86b8-b0c8ca8e4b8a.png)

**Comment by manuelwedler** [comment]
The problem is that Web3 2.x does not support Goerli network. I already created a PR on the Web3 repo (https://github.com/ethereum/web3.js/pull/3368) to support it, but I have been told that they are not working on 2.x at the moment.

**Comment by kelsos** [comment]
@manuelwedler I also asked in Gitter about the plans for web3.js 2.x but got no answers. Their plan is to move to 2.x at some point but until then we are stuck with an unmaintained branch so it's a hard decision. 

I am not sure how easy it would be to go with the 1.x branch until 2.x is supported again, due to the batching being too reliant on the library internals. 

One possible solution would be to figure out if the batching mechanism can be rewritten without depending on the internal working of web3.js, but I am not aware of the effort required for that.

Another possible solution would be to move away from the HTTP API and use the WebSocket API, this would certainly remove the need for batching, but requires more coordination and update of the documentation for people to use it, which makes it a bit more complicated.

**Comment by christianbrb** [comment]
Is it just the ENS support? Could we drop it?

**Comment by kelsos** [comment]
@christianbrb ENS support not working is caused due to us being stuck in the v2.0 of web3.js branch that has no updates since August 2019. Initially, this branch was versioned as 1.0.0-beta.x. The maintainer started doing a complete re-write but they kept the versions 1.0.0-beta.x.

The community didn't like that and after discussions, it was decided that the latest betas with the rewrite would become the 2.x branch which had one release in August and the beta before the rewrite that was based on the legacy code was the v1.x branch that is actively maintained at the moment. 

We could check if the older implementation of the BatchManager (https://github.com/raiden-network/webui/commit/f1c1fdfe62b1206b939aaeae832215b57dbfdd74) still works with the 1.x release.

**Comment by christianbrb** [comment]
1. Go with https://github.com/ethereum/web3.js/releases/tag/v1.2.6

2. > We could check if the older implementation of the BatchManager (https://github.com/raiden-network/webui/commit/f1c1fdfe62b1206b939aaeae832215b57dbfdd74) still works with the 1.x release.
