### ISSUE TITLE
Add payment identifier to transfer dialog

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#345]
### Description
We omitted the possibility to set the payment identifier for a transfer in the redesign. We should add it again.

### Tasks
- [x] Design
- [ ] Implement

**Comment by kelsos** [comment]
Like we discussed in the past when we first added this I think that this should be optional and not visible by default. The manually set payment identifier would only be used in specific use-cases. 

And at least for me, the payment identifier should not be something the user has to fill by hand. There should be a way to fill it automatically based on some action etc.

**Comment by lullis** [comment]
The whole mechanism for hub20 to work as a payment gateway relies on the user being able to set the payment identifier.

Any payment request that can be routed by Raiden gets a randomly generated integer by Hub20, which the user then has to fill on the webUI in order for the payment to be registered. Due to JS number system, the number generated is on the range of (1, 2^53).

 IIRC. payment identifiers themselves are normal bigint on Raiden, so they could go up to 2^256.

A suggestion would be to have the webUI generate the payment identifier and use `new Date().getTime()` as default. This way you can get an integer that can increase on a predictable range (I mean, 2^41 would work until 2039, 2^48 until the year 10889...) and then I could for example ensure that the payment identifier is generated only between 2^48 and 2^53, which for the purposes of payment identification are more than safe.

**Comment by manuelwedler** [comment]
Thanks for the explanation. 

Currently the WebUI generates the payment identifier by taking the current time in seconds mutliplied by 1000 and adding a random number in the range of 0 - 999. So the identifier already falls in your range.

**Comment by sashseurat** [comment]
@manuelwedler here is a quick draft showing how the identifier can be added in a subtle way:
https://www.figma.com/proto/PlHAageRNIBM1G1VcbDA8c/webui-transfer-identifier?node-id=1%3A3&viewport=650%2C1248%2C2&scaling=min-zoom
