### ISSUE TITLE
Important - Show on-chain DAI and RDN in UDC in the WebUI

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/webui#485]
I love the new WebUI!

We have a little problem when people use the Wizard and then end up in the new WebUI. 

![First View](https://user-images.githubusercontent.com/35031754/85040493-281f5780-b189-11ea-8deb-515930e11ff6.png)

Basically, I as a user was confused. The Wizard exchanged my ETH to DAI and RDN but this is not shown here. 

I would love to see (under the on-chain ETH balance top left) my on-chain DAI balance and my RDN balance in the UDC. 

Can you implement that?

**Comment by manuelwedler** [comment]
Thanks for the issue. That's indeed a big problem. 

I think showing a lot of balances in the top can be confusing the to user. @sashseurat might also have an opinion on this. 

What balance would we show on a testnet instead of the DAI? I think we should find a way to show the on-chain balances of all tokens that the user owns. At the moment they could only see it in the deposit and open channel dialogs. 
A solution could be that we only show the on-chain balance for the token that is currently selected. We could add routing for the token selection, so the wizard can open the WebUI with DAI preselected.

The UDC balance should be straight forward, but we first need a way to get the UDC address from the client: https://github.com/raiden-network/raiden/issues/5407
When we have it, we could consider to implement other UDC functionalities: https://github.com/raiden-network/webui/issues/195, https://github.com/raiden-network/webui/issues/154 and deposit to UDC.

**Comment by sashseurat** [comment]
@christianbrb Here is a draft of the balances in their different states ready for review:
![Deposited](https://user-images.githubusercontent.com/32264127/85855113-01c77080-b7b6-11ea-8358-8df25241221c.png)
![On-Chain](https://user-images.githubusercontent.com/32264127/85855116-03913400-b7b6-11ea-9b13-2efb1a35c9db.png)

**Comment by christianbrb** [comment]
@sashseurat Great thanks 😊👍🏻 Looks good, but I don’t know the exact requirements.

@Dominik1999 Could you take a look?

**Comment by Dominik1999** [comment]
looks perfect, it show the information that we need to see thanks @sashseurat

**Comment by sashseurat** [comment]
After discussions with Manuel, here are two drafts (second is a click dummy), for the Mainnet & Tetnet views of the on-chain balances:
https://www.figma.com/file/K5EwT9m73L6v3T9imc1jo3/Raiden-WebUI?node-id=0%3A1

**Comment by sashseurat** [comment]
Screenshots:
mainnet
![Mainnet](https://user-images.githubusercontent.com/32264127/86457679-b6204400-bd2c-11ea-911e-e693537ae09c.png)
testnet
<img width="1294" alt="Screenshot 2020-07-03 at 12 56 50" src="https://user-images.githubusercontent.com/32264127/86457673-b3255380-bd2c-11ea-98aa-48be00dd0a78.png">

**Comment by Dominik1999** [comment]
pretty sweet!
