### ISSUE TITLE
Add simple replacement for connection manager

### ISSUE THREAD

**Issue by karlb** [raiden-network/webui#547]
The current connection manager is about to be removed (see https://github.com/raiden-network/raiden/issues/4730). It would be good to have a simple replacement in the WebUI.

Using it could look like this:
* User clicks "Join token network"
* UI asks PFS for suggested partners
* User enters amount of tokens to deposit and gets a preview of the recommended channel openings and deposits
* User confirms or cancels

Optional feature:
* User can select which of the suggested partners should be used by (un)checking them in the preview

This will be a lot simpler and more transparent then the current process of joining a TN. As a downside, there won't be a mechanism to ensure deposits in both directions. This is ok if the user only wants to pay, but it will be a problem when receiving payments.

**Comment by sashseurat** [comment]
@manuelwedler & @karlb 
After discussing this with Manuel, here is a static design draft for the dialog concept:
![201019 Quick Connect Redesign Concept](https://user-images.githubusercontent.com/32264127/96431049-46fb2c80-1203-11eb-8891-70a4d103cd7b.png)

- Each suggested connection can lead to its network graph visualizing the connection for the user (external link)
- The ? icon nest to total deposit can lead to/show info on this logic and what is expected of user
- Slider for each connection is moved by user, displaying the deposit sum in the adjacent input field - user can also type in input field instead of dragging slider
- The default is the total amount divided equally between suggested connections

**Comment by karlb** [comment]
Looks good!

I suggest that when a user draws the slider fully to the left or enters zero, that no channel gets created (instead of creating a channel and not depositing any funds).

**Comment by manuelwedler** [comment]
Perfect, that's what I had in mind. We can make the partner appear transparent or grey in that case, so it is clear that no channel will be created.
